name: goloader Testing

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:    
  build:
    env:
      GOPATH: ${{ github.workspace }}
      GO111MODULE: auto
    strategy:
      fail-fast: false
      matrix:
        go-version: [1.8.x, 1.9.x, 1.10.x, 1.11.x, 1.12.x, 1.13.x, 1.14.x, 1.15.x, 1.16.x, 1.17.x, 1.18.x, 1.19.x]
        os:  [ubuntu-latest, windows-latest, macos-latest]
    runs-on: ${{ matrix.os }}

    steps:
    - name: Set up Go
      uses: actions/setup-go@v2
      with:
        go-version: ${{ matrix.go-version }}
        
    - name: Rename cmd/internal
      shell: sh
      run:         
        cp -r $GOROOT/src/cmd/internal $GOROOT/src/cmd/objfile
        
    - name: Checkout code
      uses: actions/checkout@v2
      with:
        path: ${{ env.GOPATH }}/src/github.com/${{ github.repository }}
      
    - name: Build
      run:
        go build github.com/pkujhd/goloader/examples/loader
        
    - name: Compile const.go
      shell: sh
      run:
        go tool compile $GOPATH/src/github.com/pkujhd/goloader/examples/const/const.go
        
    - name: Compile base.go
      shell: sh
      run:
        go tool compile $GOPATH/src/github.com/pkujhd/goloader/examples/base/base.go
        
    - name: Test base.o
      run: 
        ./loader -o base.o -run main.main
        
    - name: Test const.o
      run:
        ./loader -o const.o -run main.main
